baseURL = "https://beta.kurzius.net/"
languageCode = "en-us"
title = "Mr. Kurzius"
theme = "book"

[params]
BookMenuBundle = '/menu'
BookTheme = 'dark'
BookToc = false
BookDateFormat = 'January 2, 2006'

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true
