baseURL = "https://beta.kurzius.net/"
languageCode = "en-us"
title = "Mr. Kurzius"
theme = "book"

#[markup.goldmark.renderer]
#unsafe= true

[params]
BookMenuBundle = '/menu'
BookTheme = 'dark'
BookSection = '*'
bookToc = false